Siddhant Bhalerao

B B3 43

ML Practical-4

In [1]:
import pandas as pd
df=pd.read_csv("enjoy.csv")

In [2]:
df.head(30-24)

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2   Rainy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes
4   Sunny    Cold   Normal    Weak  Warm     Same         No
5  Cloudy    Warm   Normal    Weak  Warm     Same         No

In [3]:
df.tail(20)

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2   Rainy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes
4   Sunny    Cold   Normal    Weak  Warm     Same         No
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [7]:
import numpy as np

def find_s(X, y):
    hypothesis = None
    print("Initial Hypothesis:", hypothesis)
    
    for i in range(len(X)):
        # Process ONLY positive examples ('Yes')
        if y[i] == 'Yes':
            if hypothesis is None:
                hypothesis = X[i].copy()
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = '?'
                        
        print(f"\nAfter Training Example {i + 1} ({y[i]}):")
        print(hypothesis)
        
    return hypothesis

final_s_hypothesis = find_s(X, y)
print("\nFinal Specific Hypothesis (Find-S):", final_s_hypothesis)

Initial Hypothesis: None

After Training Example 1 (Yes):
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After Training Example 2 (Yes):
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 3 (No):
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 4 (Yes):
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 5 (No):
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 6 (No):
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 7 (Yes):
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 8 (No):
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 9 (Yes):
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 10 (Yes):
['Sunny' 'Warm' '?' '?' '?' '?']

Final Specific Hypothesis (Find-S): ['Sunny' 'Warm' '?' '?' '?' '?']

Candidate Elimination Algorithm

In [8]:
def candidate_elimination(X, y):
    num_attributes = X.shape[1]
    specific_h = X[0].copy()
    general_h = [["?" for _ in range(num_attributes)] for _ in range(num_attributes)]    
    print("Initial Specific Boundary (S0):", specific_h)
    print("Initial General Boundary (G0):", general_h)   
    for i, h in enumerate(X):
        if y[i] == "Yes":
            for x in range(num_attributes):
                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
                    general_h[x][x] = '?'
        elif y[i] == "No":
            for x in range(num_attributes):
                if h[x] != specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'
                    
        print(f"\nAfter Training Example {i + 1} ({y[i]}):")
        print("S:", specific_h)
        print("G:", general_h)
    general_h = [g for g in general_h if g != ['?'] * num_attributes]
    return specific_h, general_h

final_s, final_g = candidate_elimination(X, y)

print("\n=== FINAL BOUNDARIES ===")
print("Final Specific Boundary (S):", final_s)
print("Final General Boundary (G):", final_g)

Initial Specific Boundary (S0): ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Initial General Boundary (G0): [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 1 (Yes):
S: ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G: [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 2 (Yes):
S: ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G: [['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 3 (No):
S: ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

After Training Example 4 (Yes):
S: ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 5 (No):
S: ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G: [['?', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 6 (No):
S: ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 7 (Yes):
S: ['Sunny' 'Warm' '?' '?' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 8 (No):
S: ['Sunny' 'Warm' '?' '?' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 9 (Yes):
S: ['Sunny' 'Warm' '?' '?' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

After Training Example 10 (Yes):
S: ['Sunny' 'Warm' '?' '?' '?' '?']
G: [['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

=== FINAL BOUNDARIES ===
Final Specific Boundary (S): ['Sunny' 'Warm' '?' '?' '?' '?']
Final General Boundary (G): [['Sunny', '?', '?', '?', '?', '?']]